### PR TITLE
New module - Skyhold flight NPC

### PR DESCRIPTION
**Pull request by tiker**
This is for the flight master (Stormflight Master) NPC in Skyhold (class hall for Warriors in Legion).

There's probably a better icon to use than the flight master boot but I don't know what to use for this at the moment.

"Broken Shore" is one of the destinations but it is already translated so I left it where it is.

Before:
wowscrnshot_011519_193546

After:
wowscrnshot_011519_193631

### CODE REVIEW

**Comment by p3lim** [comment]
Not having played warrior myself, are all the destinations available from the start?

Also, the flight master icons would be my choice as well.

**Comment by tiker** [comment]
Now that I think about it, my Warrior hasn't been to Argus yet.  I doubt that there will be an option for Argus since you can't fly there with a normal flight (bird) but I'll check that tonight to confirm.

**Comment by p3lim** [comment]
Any update on Argus?

**Comment by tiker** [comment]
My Warrior hasn't fully unlocked all of Argus but so far, nothing.  I don't think there will be a port here.

**Comment by p3lim** [comment]
Alright.

**Comment by tiker** [comment]
The changes for Highmountain does not work.

	[addon:GetMapName(750)]	= {zone = 750, x = 0.3853, y = 0.4554}, -- Highmountain


The text from the NPC says Highmountain but you end up in Thunder Totem (sub zone in Highmountain which is zone 750).

**Comment by p3lim** [comment]
I'd rather add the relative coordinate in Highmountain than adjusting the localization.
https://github.com/p3lim-wow/InteractiveWormholes/commit/c73d160d4fe85f81855014c2dc59d032aefa027d

**Pull request merged**
