### PR TITLE
Add missing teleports to Animaflow Teleporter

### PR DESCRIPTION
**Pull request by jrowles**

### CODE REVIEW

**Comment by p3lim** [comment]
These were added in 9.1.5?

**Comment by p3lim** [comment]
Thanks!

**Comment by Emoosch** [comment]
Hey,

in the maw, the animaflow teleporter are bugged. (i guess)
it opens the map, but it want show the ports and i cant click on a location.

its just the "normal" map.
i use LTM (LeatrixMaps) if this can cause the problem.

**Comment by p3lim** [comment]
image

Works just fine for me, so it might be a compatibility problem.

**Comment by Emoosch** [comment]
Oh okay, thanks and sorry. :)
I will test the compatibility problem.

**Pull request merged**
