### PR TITLE
Darkshore Warfront (Alliance) flights

### PR DESCRIPTION
**Pull request by tiker**
Adds support for the Alliance flights during the Darkshore Warfront (attack phase).

I'm sure there will be a Horde equivalent but I don't have a Horde character high enough to find out.

### CODE REVIEW

**Comment by p3lim** [comment]
I'll take the horde ones once we get to attack. Thank you for the contribution.

Would you mind getting the coordinates of the flight master NPC as well? That way I can add routes to the destinations (I'll implement that).

**Comment by tiker** [comment]
The NPC (Fidelio Featherleaf) is at 0.4861 0.3447.

It's a 1 way flight from this NPC to the destinations.
wowscrnshot_121518_094459

**Comment by p3lim** [comment]
Thank you.

**Comment by p3lim** [comment]
I tweaked the locations a bit and added a missing one, please test it when Darkshore comes back into rotation.

Also, would you mind contributing to the Arathi Highlands warfront flight paths?
https://github.com/p3lim-wow/InteractiveWormholes/blob/master/modules/Warfronts.lua#L17-L22

I've restructured the addon a bit to (hopefully) be easier to contribute to.

**Comment by tiker** [comment]
Sure thing.  I'll update this thread once the Alliance is attacking again.  Thanks.

**Comment by p3lim** [comment]
Thanks.

**Pull request merged**
